version: "3.8"

services:

  go-ping-pong-instance-1:
    build:
      context: ./1
      dockerfile: Dockerfile
    image: websalad/go-ping-pong-service:instance1
    container_name: go-ping-pong-1
    environment:
      - APP_PORT=8080
      - PONG_MESSAGE=Greetings from Go App Instance 1!
    ports:
      - "8091:8080"
    restart: always

  go-ping-pong-instance-2:
    build:
      context: ./2
      dockerfile: Dockerfile
    image: websalad/go-ping-pong-service:instance2
    container_name: go-ping-pong-2
    environment:
      - APP_PORT=8080
      - PONG_MESSAGE=Hello from Go App Instance 2!
    ports:
      - "8092:8080"
    restart: always
